### ISSUE TITLE
Social Auth

### ISSUE THREAD

**Issue by Butonix** [leslie-alldridge/docker-django-react-redux-webpack-boilerplate-heroku#1]
Can you add an example of authorization through social networks? 
rest-auth
allauth

**Comment by leslie-alldridge** [comment]
I've added the boilerplate and tested the api endpoints here and json responses

https://django-rest-auth.readthedocs.io/en/latest/api_endpoints.html

you should be able to dispatch api calls from react to these endpoints with the correct credentials.

**Comment by leslie-alldridge** [comment]
If you get stuck setting it up let me know what you've tried and I can attempt to implement an example when I get some spare time this weekend.

**Comment by Butonix** [comment]
> If you get stuck setting it up let me know what you've tried and I can attempt to implement an example when I get some spare time this weekend.

In backend using allauth without any problems happening authorization via VK
I don't understand how to send data from frontend. Please, when you have time, make an example on your code. Thanks

**Comment by leslie-alldridge** [comment]
@Butonix I found an old repo someone made with this all set up. Sadly it's broken but I think it "might" be faster for me to fix and update their repo. I'll keep you posted...

**Comment by Butonix** [comment]
> @Butonix I found an old repo someone made with this all set up. Sadly it's broken but I think it "might" be faster for me to fix and update their repo. I'll keep you posted...

Thanks. I'll Wait. I saw that repo, too. It's broken.

**Comment by leslie-alldridge** [comment]
I got the back + front ends working but had trouble with the form submitting correctly. Using postman only some routes were working. I wasn't able to get authenticated. 

I was thinking of trying https://github.com/bkawan/django-auth-with-social next, have you tried this one before?

**Comment by Butonix** [comment]
> I got the back + front ends working but had trouble with the form submitting correctly. Using postman only some routes were working. I wasn't able to get authenticated.
> 
> I was thinking of trying https://github.com/bkawan/django-auth-with-social next, have you tried this one before?

it only works on the backend. but not on the front
I have now so configured all on Vkontakte
it works. I can log in at http://localhost:8000/accounts/vk/login/
but how to send data from frontend. to get a modal window with authorization and sending data to the server. I never understood.)

**Comment by leslie-alldridge** [comment]
@Butonix  I followed this article and it makes so much more sense now! 

https://wsvincent.com/django-allauth-tutorial-custom-user-model/

I'm only using the html forms (not react) but I'll try to implement react on top of this now that I understand the urls and requests a lot better. 

I'll be in touch

**Comment by Butonix** [comment]
> @Butonix I followed this article and it makes so much more sense now!
> 
> https://wsvincent.com/django-allauth-tutorial-custom-user-model/
> 
> I'm only using the html forms (not react) but I'll try to implement react on top of this now that I understand the urls and requests a lot better.
> 
> I'll be in touch

didn't try to react to do?

**Comment by leslie-alldridge** [comment]
Yup I've added react but just need to do social auth now, been busy at work lately haven't had much time

**Comment by Butonix** [comment]
> Yup I've added react but just need to do social auth now, been busy at work lately haven't had much time

Hey. Please add an example to your code with authorization through social networks
